url: https://carolinebeyne.com
baseurl: 

# Site settings
title: CarolineBeyne.com
email: contact@carolinebeyne.com
description: "Caroline Beyne - Computer Engineer - Ingénieure Informatique - Dreaming of working for the VFX industry"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: F05F40
  secondary: eb3812
  secondary-yellow: FED136
  secondary-dark: 333
  secondary-purple: C348BA
