url: https://carolinebeyne.com

# Site settings
name: Caroline Beyne
title: CarolineBeyne.com
email: contact@carolinebeyne.com
description: "Caroline Beyne - Computer Engineer - Ingénieure Informatique - VFX TD"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: F05F40
  secondary: eb3812
  secondary-dark: 333
  secondary-yellow: FED136

# More
highlighter: rouge

default_locale:     "en"
authorized_locales: ["en", "fr"]
